src/components v2/Label/Label.stories.js
src/components v2/Label/Label.vue
src/components v2/Label/index.ts
src/components v2/index.ts
src/theme/styles/colors.theme.json
src/theme/styles/label.theme.json
src/utils/parseBrandingJson.js

ticket: https://verteva.atlassian.net/browse/PLAT-24

[feat(PLAT-24)]: Label v2 component.

---

.github/workflows/run-tests.yml
src/components/ContentCard/ContentCard.spec.js
src/components/InputBasicSelect/InputBasicSelect.spec.js

Simple test runner on pull request. 
ticket: https://verteva.atlassian.net/browse/PLAT-58

[chore(PLAT-58)]: Run test suite on pr

---

.github/pull_request_template.md

Default pull request template.

[chore(PLAT-93)]: default pull request template

---

package-lock.json
src/components v2/Card/Card.spec.js
src/components v2/Card/Card.stories.js
src/components v2/Card/Card.vue
src/components v2/Card/index.ts
src/components v2/index.ts
src/components/InputBasicSelect/InputBasicSelect.spec.js
src/theme/styles/card.theme.json
src/theme/styles/variables.theme.json

Ticekt: https://verteva.atlassian.net/browse/PLAT-36
- v2 Card component

[feat(PLAT-36)]: V2 Card component

---

CHANGELOG.md
package.json
src/utils/parseBrandingJson.js

ticket: https://verteva.atlassian.net/browse/PLAT-118
_Include a short log of the changes_
- Simplified the template parser for safari and added error handling.

[fix(PLAT_118)]: simplified regex for safari

---

CHANGELOG.md
package.json

Fix the broken release which went to npm. Updated version for redeploy to npm.

[fix] Fix broken release version

---

.commitlintrc.json
.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package-lock.json
package.json

Added commit linting and lint-staged on commit hooks. This is a requirement to enforce semantic versioning.
ticket: https://verteva.atlassian.net/browse/PLAT-94
_Include a short log of the changes_
- Add Husky
- Add lint-staged with husky pre-commit hook.
- Add commitlint with husky commit-message hook.

chore(PLAT-94): added commit lint and lint-staged

---

.releaserc.json

It Fixes the message length error. Release notes are saved in the changelog so we don't require them in the release.

fix: updated semantic release commit message

---

package-lock.json
themeFileLocation.js

fix: themelocation fix

---

.storybook/webpack.config.js
src/utils/themeFileLocation.js

ticket: https://verteva.atlassian.net/browse/PLAT-65
This allows storybook to build online

fix: fixed build for storybook build

---

.github/pull_request_template.md
.releaserc.json
src/utils/figmaTheme/parseFigmaTheme/parseFigmaTheme.js
src/utils/figmaTheme/templateResolvers/parsers/boxShadowParser.js
src/utils/figmaTheme/templateResolvers/parsers/index.js
src/utils/figmaTheme/templateResolvers/test/templateResolvers.spec.js
src/utils/figmaTheme/templateResolvers/test/themeRoots.js

ticket: https://verteva.atlassian.net/browse/PLAT-203
Added the missing basic parsers.
Updated the shadow parser. It now runs for both objects and arrays. Updated tests to match. 
CHORE WORK:
removed the changelog items from the PR template (this is now automated)
removed `[skip ci]` from the changelog/version bump commit messages so that it runs ci/cd workflows

fix: added additional parser types and fixed shadow parser

---

src/components v2/Forms/Atoms/Message/Message.spec.js
src/components v2/Forms/Atoms/Message/Message.stories.js
src/components v2/Forms/Atoms/Message/Message.vue
src/components v2/Forms/Atoms/Message/index.ts
src/theme/styles/inputMessage.theme.json

ticket: https://verteva.atlassian.net/browse/PLAT-265

feat: input message atom component

---

src/components v2/Forms/Atoms/ErrorMessage/ErrorMessage.vue
src/components v2/Forms/Atoms/ErrorMessage/index.ts
src/components v2/Forms/Atoms/InputMessage/InputMessage.spec.js
src/components v2/Forms/Atoms/InputMessage/InputMessage.stories.js
src/components v2/Forms/Atoms/InputMessage/InputMessage.vue
src/components v2/Forms/Atoms/InputMessage/index.ts
src/components v2/Forms/Atoms/Label/Label.vue
src/components v2/Forms/Atoms/Message/index.ts
src/components v2/Forms/Molecules/FormControl/FormControl.spec.js
src/components v2/Forms/Molecules/FormControl/FormControl.stories.js
src/components v2/Forms/Molecules/FormControl/FormControl.vue
src/components v2/Forms/Molecules/FormControl/index.ts
src/stories/changelog.stories.mdx
src/theme/styles/inputError.theme.json
src/theme/styles/inputMessage.theme.json

ticket: https://verteva.atlassian.net/browse/PLAT-263

feat: PLAT-263: form control molecule

---

package-lock.json
package.json
src/utils/figmaTheme/templateResolvers/parsers/colorParser.js
src/utils/figmaTheme/templateResolvers/parsers/index.js
src/utils/figmaTheme/templateResolvers/test/templateResolvers.spec.js
src/utils/figmaTheme/templateResolvers/test/themeRoots.js

No jira story. Color parser update for RGBA values.

fix: updated color parser

---

src/components v2/Forms/Molecules/FormControl/FormControl.stories.js
src/components v2/Forms/Molecules/FormControl/FormControl.vue

chore: updated props for formControl

---

package-lock.json
src/utils/parseBrandingJson.js
src/utils/test/__snapshots__/injectThemeCssVariables.spec.js.snap
src/utils/test/__snapshots__/parseBrandingJson.spec.js.snap
src/utils/test/injectThemeCssVariables.spec.js
src/utils/test/parseBrandingJson.spec.js
src/utils/test/parsedTheme.json
src/utils/test/rawTheme.json
src/utils/themeFileLocation.js

chore to update test coverage:
Added test coverage for our two missing files.
NOTE: ignored the `themeFileLocation.js` file since its a dev helper. `require.context` is unavailable in jest and to create a mock to see if it calls when I set globals does not test its functionality.

test: updated tests for utils. 100% functional coverage

---

src/utils/figmaTheme/buildThemeFiles/__snapshots__/buildThemeFiles.spec.js.snap
src/utils/figmaTheme/buildThemeFiles/buildThemeFiles.spec.js
src/utils/figmaTheme/getFigmaTheme/getFigmaTheme.js
src/utils/figmaTheme/getFigmaTheme/test/__snapshots__/getFigmaTheme.spec.js.snap
src/utils/figmaTheme/getFigmaTheme/test/getFigmaTheme.spec.js
src/utils/figmaTheme/mockThemeFiles/testFileObjects.js
src/utils/figmaTheme/parseFigmaTheme/parseFigmaTheme.js
src/utils/figmaTheme/parseFigmaTheme/test/__snapshots__/parseFigmaTheme.spec.js.snap
src/utils/figmaTheme/parseFigmaTheme/test/parseFigmaTheme.spec.js
src/utils/figmaTheme/parseFigmaTheme/test/rawSemanticTheme.json
src/utils/figmaTheme/parseFigmaTheme/test/rawSourceTheme.json

ticket: https://verteva.atlassian.net/browse/PLAT-266

PLAT-266: feat: added source file exclusion from parser

---

src/components v2/index.ts

fix: fixed imports for Molecules

---

.github/workflows/preview-build.yml
.gitignore
scripts/gets3files.sh

Pipeline switched to cx-theme files.

chore: switched pipeline to cx-themes

---

.github/workflows/preview-build.yml
.storybook/preview.js
.storybook/theme-bar.scss
src/components/store.ts

chore: Updates to the themebar.
- The theme bar now stores its value in a store which persists when you swap between components.
- The theme bar now loads the correct file on startup.

chore: improvement to the theme bar selector

---

src/components/Dialog/Dialog.vue

fix: add focus to Dialog

---

.github/workflows/release.yml

fixes node version in release pipeline

fix: node version in release pipeline

---

src/components v2/Atoms/Forms/Checkbox/Checkbox.stories.js
src/components v2/Atoms/Forms/CheckboxGroup/CheckboxGroup.stories.js
src/components v2/Atoms/Forms/InputMessage/InputMessage.vue

small storybook update and input message fix.

fix: checkboxes fixed with styles

---

.github/workflows/run-tests.yml
.gitignore
jest.config.js
package-lock.json
package.json
sonar-project.properties

chore: added sonar project properties and jest-sonar-reporter package

---

.github/workflows/run-tests.yml

chore: added develop branch to build workflow

---

src/components v2/Atoms/Forms/RadioButton/RadioButton.vue
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.vue

missing name attribute for the input fields

fix: radio button missing name attribute binding

---

sonar-project.properties

chore: updated sonarcloud exclusions

---

src/components v2/Atoms/Forms/RadioButton/RadioButton.vue
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.stories.js
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.vue

JIRA: https://verteva.atlassian.net/browse/PLAT-289
a new solution to handle radio buttons width for amp

fix: select radio button full width

---

LICENCE

feat: add the MIT licence

---

sonar-project.properties

chore: improvements to coverage scan

---

sonar-project.properties

chore: remove types from coverage

---

src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.stories.js
src/components v2/Atoms/Forms/Toggle/Toggle.spec.js
src/components v2/Atoms/Forms/Toggle/Toggle.stories.js
src/components v2/Atoms/Forms/Toggle/Toggle.vue
src/components v2/Atoms/Forms/Toggle/index.ts
src/components v2/Molecules/Forms/InputToggle/InputToggle.spec.js
src/components v2/Molecules/Forms/InputToggle/InputToggle.stories.js
src/components v2/Molecules/Forms/InputToggle/InputToggle.vue
src/components v2/Molecules/Forms/InputToggle/index.ts
src/components v2/index.ts

ticket: https://verteva.atlassian.net/browse/PLAT-228

feat: toggle component

---

src/components v2/Atoms/Forms/InputText/InputText.vue
src/components v2/Molecules/Forms/InputText/InputText.vue

added blur event as OB has in issue with passing values

fix: input text component blur event added for

---

src/components v2/Atoms/Forms/RadioButton/RadioButton.vue

moved the radio circle within the label as it's not currently clickable

fix: unable to select the radio button circle

---

src/components v2/Molecules/Forms/NumberInput/NumberInput.vue

fix: number input is now centered

---

src/components v2/Atoms/Components/BackDrop/BackDrop.spec.js
src/components v2/Atoms/Components/BackDrop/BackDrop.stories.js
src/components v2/Atoms/Components/BackDrop/BackDrop.vue
src/components v2/Atoms/Components/BackDrop/index.ts
src/components v2/Atoms/Components/Headline/Headline.spec.js
src/components v2/Atoms/Components/Headline/Headline.stories.js
src/components v2/Atoms/Components/Headline/Headline.vue
src/components v2/Atoms/Components/Headline/index.ts
src/components v2/Molecules/Components/Dialog/Dialog.spec.js
src/components v2/Molecules/Components/Dialog/Dialog.vue
src/components v2/Molecules/Components/Dialog/index.ts
src/components v2/Molecules/Components/Dialog/types.ts
src/components v2/index.ts

(fix: update dialog with cx-branding)

fix: update dialog with cx-branding

---

src/components v2/index.ts

fix: added/updated list items export names

fix: update export names of list items

---

src/components v2/Atoms/Components/VSelect/Indicator/Indicator.vue
src/components v2/Atoms/Components/VSelect/InputSearch/InputSearch.vue
src/components v2/Atoms/Components/VSelect/SelectedOption/SelectedOption.vue
src/components v2/Atoms/Forms/InputAutoComplete/InputAutoComplete.stories.js
src/components v2/Atoms/Forms/InputAutoComplete/InputAutoComplete.vue
src/components v2/Atoms/Forms/InputSelect/InputSelect.spec.js
src/components v2/Atoms/Forms/InputSelect/InputSelect.stories.js
src/components v2/Atoms/Forms/InputSelect/InputSelect.vue
src/components v2/Molecules/Forms/InputSelect/InputSelect.stories.js
src/components v2/Molecules/Forms/InputSelect/InputSelect.vue

issues that were found during OB-web integration

fix: input select fixes onboarding-web integration

---

CHANGELOG.md
package.json

merge main into dev (currently blocking dev->main)

main -> dev

---

src/components v2/Atoms/Components/Button/Button.vue

fix: removed slot rendering in button that caused <template> tags

---

src/components v2/Atoms/Forms/RadioButton/RadioButton.vue

fix: update radio button checked background

fix: update radio button checked background

---

src/components v2/Atoms/Components/Headline/Headline.vue

fix: heading 1 downgrade

---

src/utils/figmaTheme/templateResolvers/parsers/colorParser.js

fix: color parser update to allow for whitespaces

---

src/components v2/Atoms/Components/VSelect/SelectedOption/SelectedOption.stories.js
src/components v2/Atoms/Components/VSelect/SelectedOption/SelectedOption.vue
src/components v2/Atoms/Forms/InputAutoComplete/InputAutoComplete.stories.js
src/components v2/Atoms/Forms/InputAutoComplete/InputAutoComplete.vue

Makes the items overflow ellipsis. Check the build out to see its effect.

fix: overflow elpisis for long text

---

src/components v2/Atoms/Forms/InputDate/InputDate.vue
src/components v2/Atoms/Forms/InputText/InputText.vue
src/components v2/Molecules/Forms/InputDate/InputDate.vue
src/components v2/Molecules/Forms/InputText/InputText.vue

fix: prevent non numbers being typed inputText, inputDate

---

src/components v2/Atoms/Forms/InputPhone/InputPhone.vue

Phone bug fix

---

src/components v2/Molecules/Forms/InputPhone/InputPhone.vue

Phone props bind

---

src/components v2/Atoms/Forms/InputSelect/InputSelect.vue
src/components v2/Molecules/Forms/InputSelect/InputSelect.vue

fix: passthrough returnObj

---

src/utils/figmaTheme/getFigmaTheme/getFigmaTheme.js

fix: parser fix

---

package.json

chore(release): update release 0.17.1

---

package.json
src/components v2/Atoms/Forms/InputAutoComplete/InputAutoComplete.vue
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.stories.js
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.vue
src/components v2/index.ts
src/utils/fontAwesome/library.js

Fixes for AutoComplete, Radio Button Group (stacking) and exporting P2ErrorMessage

Fixes for AutoComplete, Radio Button Group (stacking) and exporting P2ErrorMessage

---

package.json
src/components v2/Atoms/Forms/RadioButtonGroup/RadioButtonGroup.vue

Fix for Radio Button Group stacked default

Fix for Radio Button Group stacked default
